#ifndef LOGIKA_DEFS_H
#define LOGIKA_DEFS_H

#define LOGIKA_USE_CONNECTIONS
#define LOGIKA_USE_CONNECTIONS_SERIAL
#define LOGIKA_USE_CONNECTIONS_NETWORK
#define LOGIKA_USE_LOGGER
#define LOGIKA_USE_METERS
#define LOGIKA_USE_METERS4
#define LOGIKA_USE_METERS4L
#define LOGIKA_USE_METERS4M
#define LOGIKA_USE_PROTOCOL_M4
#define LOGIKA_USE_RESOURCE_CONVERTERS

#endif // LOGIKA_DEFS_H
